### ISSUE TITLE
Support for multiple windows

### ISSUE THREAD

**Issue by orschiro** [orschiro/Alt-Q-Switch-Tabs-Keyboard-Shortcut#17] opened 2018-02-28 08:16 UTC
Should work with multiple windows too.

**Comment by orschiro** [comment] 2018-03-04 13:09
@Bibernull I cleaned up the code in the recent commit to prepare for this issue. 

Any idea how we could add support for switching between multiple windows?

**Comment by frankyjuang** [comment] 2018-03-10 13:29
@orschiro i can think of two different ways of supporting multi-window. 
- users have global last tabs among all windows
- users have independent last tabs for each window

Any ideas which is prefered?

**Comment by orschiro** [comment] 2018-03-10 19:13
@frankyjuang in my opinion we should encourage people to maintain independent last tabs for each window and thus use windows to structure their work tasks. Accordingly, move a tab to the window where it belongs to if you want to switch between it. 

Do you agree with me?

**Comment by frankyjuang** [comment] 2018-03-11 08:40
Sounds really great for me. Will leave it until other bugs are solved.

**Comment by orschiro** [comment] 2018-03-18 17:11
@frankyjuang currently testing the latest source in preparation of version 11. 

However, the extension stops working after a while even in single window mode. 

Can you please test too the latest commit?

**Comment by frankyjuang** [comment] 2018-03-19 10:13
Really? Did you update to the HEAD? It works perfect for me after using couple of days with three windows. No error was logged. Or can you provide the logs from the background page console?
![image](https://user-images.githubusercontent.com/6175880/37589790-36bbb6e6-2ba1-11e8-8ca0-6bb1b06a3070.png)

**Comment by orschiro** [comment] 2018-03-19 12:46
Was able to capture this:

https://youtu.be/FJ0eQWhJCTY

**Comment by frankyjuang** [comment] 2018-03-20 07:39
Can you set the log level to all levels (including verbose)? More debugging infos will then be displayed.
![image](https://user-images.githubusercontent.com/6175880/37641493-e55f1e50-2c54-11e8-8f00-542f639abbcc.png)

**Comment by orschiro** [comment] 2018-03-20 14:24
@frankyjuang done. Does this produce any new insights?

https://youtu.be/-ThiBZ_09-k

**Comment by frankyjuang** [comment] 2018-03-20 15:38
@orschiro I really can't tell....the error just came from nowhere.
Add this line right at the beginning of function `removeTabFromWindow` (Ln. 130).
```
console.warn(windows, windowId, tabId, currentTabId);
```
and see what it says when the mystery occurs.

**Comment by orschiro** [comment] 2018-03-21 09:03
Hope it helps!

Screencast: https://youtu.be/EFYwx-vlv04

**Comment by frankyjuang** [comment] 2018-03-24 05:27
Really weird...It seems that when you open a new tab in the background at 0:55, a `onActivated` event is triggered on the same page. How did you open the new tab in the background? I saw a cute image popup. Did you use some extensions that might related to this behavior? 

Btw, my guess about glitch due to tab removal is wrong. The extra `console.warn` is totally useless 😭 
This time please add it right at the beginning of function `chrome.browserAction.onClicked.addListener`.
```
console.warn(windows, currentWindowId, tab, currentTabId);
```
Let's see what we can do about this mystery...

**Comment by orschiro** [comment] 2018-03-24 10:38
>  I saw a cute image popup. Did you use some extensions that might related to this behavior?

Good catch!

Will test if it conflicts with:

1. https://chrome.google.com/webstore/detail/wunderlist-new-tab/fgikemaeelgbhjnhnnahcpkjpafaeion
2. https://chrome.google.com/webstore/detail/open-tabs-next-to-current/gmpnnmonpnnmnhpdldahlekfofigiffh

These two I am using that my interfere here. Will let you know!

**Comment by orschiro** [comment] 2018-03-24 10:44
New screencast: https://youtu.be/H4cTBfCgoD4

**Comment by frankyjuang** [comment] 2018-03-24 14:16
I think I kind of know what happened. It's about the behavior of window manager. According to `chrome.windows.onFocusChanged`, 
> Fired when the currently focused window changes. Will be chrome.windows.WINDOW_ID_NONE if all chrome windows have lost focus. Note: On some Linux window managers, WINDOW_ID_NONE will always be sent immediately preceding a switch from one chrome window to another.

[reference](https://developer.chrome.com/extensions/windows#event-onFocusChanged)

What you encountered is that the window manager seemed to switch to a non-chrome window but never switch back...That's why you see the `Object -1 Object null`. `-1` means id of non-chrome window. `null` is the currentTabId if focusing on non-chrome window. And since it is all about window manager, I'm not having the same issue on macOS.

Which window manager are you using? The default one of GNOME 3? Mutter? Perhaps we should search for similar issues?

**Comment by orschiro** [comment] 2018-03-24 15:06
Well done! Yes I'm using GNOME Shell 3.26 with Mutter on Fedora 27. Going
to search the bug tracker of Chromium.

**Comment by orschiro** [comment] 2018-03-25 13:55
Ref: https://gitlab.gnome.org/GNOME/gnome-shell/issues/151

**Comment by orschiro** [comment] 2018-03-26 09:10
@frankyjuang meanwhile, how about we add a new setting to context menu for people to opt in to multiple window support? Would be disabled by default. This way people on non-Linux can already test and benefit.

**Comment by frankyjuang** [comment] 2018-03-26 16:19
This could be a short-term fix. But eventually I think multi-window support should be turned on by default.

**Comment by frankyjuang** [comment] 2018-04-03 15:54
Any updates here?

**Comment by orschiro** [comment] 2018-04-03 18:45
Unfortunately haven't heard back from the GNOME devs.

I guess next step is testing with non GNOME Linux environments and see if they are also affected.

**Comment by orschiro** [comment] 2018-04-12 09:45
@frankyjuang did some tests with GNOME 3.28 but couldn't get latest commit to work. As soon as I load unpacked, it's breaking:

![image](https://user-images.githubusercontent.com/170947/38669573-ff86c018-3e46-11e8-80c0-2d5b72e72fc4.png)

Not sure how to fix this or how to proceed.

**Comment by frankyjuang** [comment] 2018-04-29 07:34
@orschiro which chrome version are you using? I cannot reproduce on latest GNOME.

**Comment by orschiro** [comment] 2018-04-30 17:04
@frankyjuang tested with a brand new Chrome 66 profile and latest git pull. Loaded unpacked from src but still getting this annoying tabHistory error. Are you doing anything differently?

```
Error in event handler for browserAction.onClicked: TypeError: Cannot read property 'tabHistory' of undefined
    at <URL>
_generated_background_page.html:1 Error in event handler for browserAction.onClicked: TypeError: Cannot read property 'tabHistory' of undefined
    at chrome-extension://ackkikfiigagnmobecoofdoaffneiadl/background.js:65:41
```

**Comment by orschiro** [comment] 2018-05-04 07:36
Version 11 Multiple Windows has been published. Let's wait for some more user feedback! :-)

**Comment by orschiro** [comment] 2018-05-07 12:26
@frankyjuang reinstalled version 11.1 from Chrome Webstore and it breaks: https://chrome.google.com/webstore/detail/switch-recent-tabs/odhjcgnlbagjllfbilicalpigimhdcll

A number of people report similar issues:

- See [Maciej](https://chrome.google.com/webstore/detail/switch-recent-tabs/odhjcgnlbagjllfbilicalpigimhdcll/reviews)
- See also [Support](https://chrome.google.com/webstore/detail/switch-recent-tabs/odhjcgnlbagjllfbilicalpigimhdcll/support) page

**Comment by orschiro** [comment] 2018-05-07 12:45
For a temporary downgrade, see: https://github.com/orschiro/switch-recent-tabs-chrome-extension/wiki/FAQ#temporarily-downgrade

**Comment by amorpheus** [comment] 2018-05-07 14:33
My issue is that the extension will work normally after starting Chrome, but not for long. I only work with one window. After coming back to Chrome from other programs, there's no Last Tab functionality at all. If I open a new Window and close it again, I can get it to work shortly sometimes, but I haven't been able to pin down the exact behavior.

Running Windows 10 Enterprise (Build 1703) on a Xeon E3 1230-v3 with 16GB RAM.

**Comment by frankyjuang** [comment] 2018-05-07 14:52
@amorpheus can you confirm if it only happens after switching to and back from other programs? and does it occurs right after switching back? thanks

**Comment by amorpheus** [comment] 2018-05-07 15:11
Okay, I went through it again. Here's what I observed:

1. completely close Chrome including task bar icon (background task)
2. start Chrome, extension works normally
3. switch focus to another program (I just clicked the Windows task bar)
4. focus back to Chrome, immediately hit Ctrl-Q as I've set it, extension often works once, sometimes twice or not at all

My take is that it seems to be functional for only a short interval after switching back to a Chrome window.

**Comment by orschiro** [comment] 2018-05-07 15:18
@amorpheus can you check if you get the error in the console shown here: https://github.com/orschiro/switch-recent-tabs-chrome-extension/issues/17#issuecomment-380743564

**Comment by orschiro** [comment] 2018-05-07 15:26
@amorpheus do a right mouse click on the extension icon > manage extension > background page

Actually great observation! I can confirm that switching app windows breaks it after a few seconds of returning to Chrome. 

@frankyjuang any ideas why this is happening and apparently only on Windows and Linux?

**Comment by amorpheus** [comment] 2018-05-07 15:28
Alright, I see the same error as in the screenshot now.

**Comment by sxhexe** [comment] 2018-05-07 17:52
I can confirm seeing the same error as in the [screenshot ](https://github.com/orschiro/switch-recent-tabs-chrome-extension/issues/17#issuecomment-380743564).

**Comment by lvbaal** [comment] 2018-05-08 07:55
Trying to debug Alt Q not working. There seems to be no error in the backgroundpage (screenshot)
![capture](https://user-images.githubusercontent.com/4673748/39744877-eccb27d4-52a5-11e8-9c69-75c2bce8f732.PNG)

**Comment by orschiro** [comment] 2018-05-08 07:57
Thanks for all your help! I have released a temporary release 12 that reverts the changes and should work stability for you until we have solved this issue. You should get the latest version in a few minutes.

**Comment by orschiro** [comment] 2018-05-09 17:15
Here are some more debug infos from people who had troubles:

```
Client version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

Client version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

Client version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

Client version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

Client version: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

Client version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

Client version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
```

**Comment by orschiro** [comment] 2018-05-14 12:34
User feedback. 

Multiple window support should become optional, i.e. implemented with a context menu option. :-)

**Closed** 2018-10-02 11:50 UTC
Labels: enhancement
